<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251124182508 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE caught_fish (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, latitude NUMERIC(15, 13) NOT NULL, longitude NUMERIC(16, 13) NOT NULL, caught_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, length DOUBLE PRECISION DEFAULT NULL, caught_by_id INT NOT NULL, fish_species_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_70178FC31715B1D3 ON caught_fish (caught_by_id)');
        $this->addSql('CREATE INDEX IDX_70178FC369171D7 ON caught_fish (fish_species_id)');
        $this->addSql('CREATE TABLE fish_species (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE caught_fish ADD CONSTRAINT FK_70178FC31715B1D3 FOREIGN KEY (caught_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE caught_fish ADD CONSTRAINT FK_70178FC369171D7 FOREIGN KEY (fish_species_id) REFERENCES fish_species (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE caught_fish DROP CONSTRAINT FK_70178FC31715B1D3');
        $this->addSql('ALTER TABLE caught_fish DROP CONSTRAINT FK_70178FC369171D7');
        $this->addSql('DROP TABLE caught_fish');
        $this->addSql('DROP TABLE fish_species');
    }
}
